package com.clay.graphstorage.entities;

/**
 * A {@link SpecialProperty} represents an abstract {@link NodeProperty} which when detected, can perform changes in the graph or any of its nodes. For example, an "addUpdatedAtProperty" can act as a special property that adds a new property "updatedAt" with current {@link java.util.Date} as value.
 * */
public abstract class SpecialProperty <T> extends NodeProperty<T> {


	public SpecialProperty(Node node, T value) {
		super(node, value);
	} 

    /**
     * Override this method to specify changes that need to be performed on Graph or this {@link Node} represented by node.
     * */
	public abstract void executeChanges(Graph graph); 

	public boolean isAutoGenerated() {
		return false;
	}

};


